### ISSUE TITLE
IRget, IRset, PRget, PRset missing

### ISSUE THREAD

**Issue by givens** [jnagy1/IRtools#1]
## Expected behavior

* Run IRrrgmres with no error

## Actual behavior

* An error occurs to due to unidentified function.

```
>> [X, info] = IRrrgmres(A, b, options);
Undefined function or variable 'IRset'.

Error in IRrrgmres (line 127)
options = IRset(defaultopt, options);
````

## Conclusion

* IRset and other functions not in the toolbox
* Without IRset, an error occurs

## Remedy

* Provide the functions in title

**Comment by jnagy1** [comment]
Sorry about that -- the Extra folder was not uploaded correctly. Everything should be included now.
